import type { CourseListResponse } from "./types";

export const mockCourseList: CourseListResponse = {
  data: [
    {
      id: "mk-3",
      userId: '1',
      name: "Praktikum Pemrograman Berorientasi Objek",
      code: "IF403",
      lecturer: "Suheri, S.T., M.Cs",
      semester: 4,
      progress: 60,
      programmingLanguage: 'java',
    },
    {
      id: "mk-3",
      userId: '1',
      name: "Praktikum Pemrograman Berorientasi Objek",
      code: "IF403",
      lecturer: "Suheri, S.T., M.Cs",
      semester: 4,
      progress: 60,
      programmingLanguage: 'java',
    },
    {
      id: "mk-3",
      userId: '1',
      name: "Praktikum Pemrograman Berorientasi Objek",
      code: "IF403",
      lecturer: "Suheri, S.T., M.Cs",
      semester: 4,
      progress: 60,
      programmingLanguage: 'java',
    },
    {
      id: "mk-3",
      userId: '1',
      name: "Praktikum Pemrograman Berorientasi Objek",
      code: "IF403",
      lecturer: "Suheri, S.T., M.Cs",
      semester: 4,
      progress: 60,
      programmingLanguage: 'java',
    },
    {
      id: "mk-3",
      userId: '1',
      name: "Praktikum Pemrograman Berorientasi Objek",
      code: "IF403",
      lecturer: "Suheri, S.T., M.Cs",
      semester: 4,
      progress: 60,
      programmingLanguage: 'java',
    },
    {
      id: "mk-3",
      userId: '1',
      name: "Praktikum Pemrograman Berorientasi Objek",
      code: "IF403",
      lecturer: "Suheri, S.T., M.Cs",
      semester: 4,
      progress: 60,
      programmingLanguage: 'java',
    },
  ],
};
